name: build-portable

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    name: Build portable bundle (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set Python version and folder names
      - name: Set versions
        shell: pwsh
        run: |
          echo "PY_VER=3.13.9" >> $env:GITHUB_ENV
          echo "PY_EMBED=python-3.13.9-embed-amd64" >> $env:GITHUB_ENV
          echo "SUBFOLDER=labels_portable_${{ github.ref_name }}" >> $env:GITHUB_ENV
          echo "ZIP_NAME=labels_portable_${{ github.ref_name }}.zip" >> $env:GITHUB_ENV

      - name: Prepare workspace
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force portable | Out-Null
          New-Item -ItemType Directory -Force portable\wheels | Out-Null
          New-Item -ItemType Directory -Force portable\$env:SUBFOLDER | Out-Null

      - name: Download Embeddable Python
        shell: pwsh
        run: |
          $url = "https://www.python.org/ftp/python/${env:PY_VER}/${env:PY_EMBED}.zip"
          Write-Host "Downloading $url"
          Invoke-WebRequest $url -OutFile portable\embed.zip
          Expand-Archive portable\embed.zip -DestinationPath portable\$env:SUBFOLDER\${env:PY_EMBED} -Force

      - name: Create site-packages and enable import site
        shell: pwsh
        run: |
          $site = "portable\$env:SUBFOLDER\${env:PY_EMBED}\Lib\site-packages"
          New-Item -ItemType Directory -Force -Path $site | Out-Null
          $pth = "portable\$env:SUBFOLDER\${env:PY_EMBED}\python313._pth"
          Add-Content $pth "."
          Add-Content $pth "Lib\site-packages"
          Add-Content $pth "import site"

      - name: Download wheels (ReportLab + Pillow)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip download --only-binary=:all: --platform win_amd64 --python-version 313 --implementation cp --dest portable\wheels reportlab pillow
          Get-ChildItem portable\wheels

      - name: Extract wheels into site-packages
        shell: pwsh
        run: |
          $site = "portable\$env:SUBFOLDER\${env:PY_EMBED}\Lib\site-packages"
          Get-ChildItem portable\wheels\*.whl | ForEach-Object {
            Write-Host "Expanding $($_.Name) -> $site"
            Expand-Archive $_.FullName -DestinationPath $site -Force
          }

      - name: Add app files
        shell: pwsh
        run: |
          Copy-Item src\generate_labels.py portable\$env:SUBFOLDER\
          if (Test-Path src\invitados.txt) { Copy-Item src\invitados.txt portable\$env:SUBFOLDER\ }
          Copy-Item scripts\run_embed.bat portable\$env:SUBFOLDER\

      - name: Smoke test imports
        shell: pwsh
        run: |
          $py = "portable\$env:SUBFOLDER\${env:PY_EMBED}\python.exe"
          & $py -c "import sys; print(sys.version); import reportlab; import PIL; print('OK: reportlab + Pillow')"

      - name: Create zip with subfolder
        shell: pwsh
        run: |
          Compress-Archive -Path "portable\$env:SUBFOLDER" -DestinationPath "${{ env.ZIP_NAME }}" -Force
          echo "ZIP_PATH=${{ env.ZIP_NAME }}" >> $env:GITHUB_ENV

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_PATH }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
